// ============================================================
//  PHOTOS.JS — единственият файл, който трябва да редактираш
//  за да добавиш нови снимки към сайта.
//
//  Как се добавя нова снимка:
//  1. Копирай снимката в папка /img/gallery/
//  2. Добави нов ред тук по примера по-долу
//  3. Качи промените в GitHub — готово!
// ============================================================

const ALBUMS = [
  {
    id: "svatbena",
    label: "Сватбена",
    color: "#c8c8c8"
  },
  {
    id: "krustene",
    label: "Кръщене",
    color: "#c8c8c8"
  },
  {
    id: "kampanii",
    label: "Кампании",
    color: "#c8c8c8"
  },
  {
    id: "editorial",
    label: "Портрети",
    color: "#c8c8c8"
  },
  {
    id: "konceptualna",
    label: "Концептуална",
    color: "#c8c8c8"
  },
  {
    id: "portret",
    label: "Бизнес портрет",
    color: "#c8c8c8"
  },
  {
    id: "balove",
    label: "Балове",
    color: "#c8c8c8"
  },
  {
    id: "produkti",
    label: "Продукти",
    color: "#c8c8c8"
  },
  {
    id: "katalog",
    label: "Каталог",
    color: "#c8c8c8"
  }
];

const PHOTOS = [
  { file: "gallery/2.jpg", album: "kampanii", title: "La Morelle", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-01.jpg", album: "kampanii", title: "Кампания 1", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-02.jpg", album: "kampanii", title: "Кампания 2", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-03.jpg", album: "kampanii", title: "Кампания 3", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-04.jpg", album: "kampanii", title: "Кампания 4", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-05.jpg", album: "kampanii", title: "Кампания 5", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-06.jpg", album: "kampanii", title: "Кампания 6", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-07.jpg", album: "kampanii", title: "Кампания 7", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-08.jpg", album: "kampanii", title: "Кампания 8", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-09.jpg", album: "kampanii", title: "Кампания 9", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-10.jpg", album: "kampanii", title: "Кампания 10", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-11.jpg", album: "kampanii", title: "Кампания 11", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-12.jpg", album: "kampanii", title: "Кампания 12", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-13.jpg", album: "kampanii", title: "Кампания 13", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-14.jpg", album: "kampanii", title: "Кампания 14", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-15.jpg", album: "kampanii", title: "Кампания 15", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-16.jpg", album: "kampanii", title: "Кампания 16", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-17.jpg", album: "kampanii", title: "Кампания 17", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-18.jpg", album: "kampanii", title: "Кампания 18", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-19.jpg", album: "kampanii", title: "Кампания 19", tags: ["мода","кампании"], cover: true },
  { file: "gallery/kampanii-20.jpg", album: "kampanii", title: "Кампания 20", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-21.jpg", album: "kampanii", title: "Кампания 21", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-22.jpg", album: "kampanii", title: "Кампания 22", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-23.jpg", album: "kampanii", title: "Кампания 23", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-24.jpg", album: "kampanii", title: "Кампания 24", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-25.jpg", album: "kampanii", title: "Кампания 25", tags: ["мода","кампании"], cover: false },
  { file: "gallery/kampanii-26.jpg", album: "kampanii", title: "Кампания 26", tags: ["мода","кампании"], cover: false },
  { file: "gallery/1.jpg", album: "editorial", title: "Портрет 0", tags: ["мода","портрети"], cover: false },
  { file: "gallery/editorial-01.jpg", album: "editorial", title: "Портрет 1", tags: ["мода","портрети"], cover: false },
  { file: "gallery/editorial-02.jpg", album: "editorial", title: "Портрет 2", tags: ["мода","портрети"], cover: false },
  { file: "gallery/editorial-03.jpg", album: "editorial", title: "Портрет 3", tags: ["мода","портрети"], cover: false },
  { file: "gallery/editorial-04.jpg", album: "editorial", title: "Портрет 4", tags: ["мода","портрети"], cover: false },
  { file: "gallery/editorial-05.jpg", album: "editorial", title: "Портрет 5", tags: ["мода","портрети"], cover: false },
  { file: "gallery/editorial-06.jpg", album: "editorial", title: "Портрет 6", tags: ["мода","портрети"], cover: false },
  { file: "gallery/editorial-07.jpeg", album: "editorial", title: "Портрет 7", tags: ["мода","портрети"], cover: false },
  { file: "gallery/editorial-08.jpg", album: "editorial", title: "Портрет 8", tags: ["мода","портрети"], cover: false },
  { file: "gallery/editorial-09.jpg", album: "editorial", title: "Портрет 9", tags: ["мода","портрети"], cover: false },
  { file: "gallery/editorial-10.jpeg", album: "editorial", title: "Портрет 10", tags: ["мода","портрети"], cover: false },
  { file: "gallery/editorial-11.jpg", album: "editorial", title: "Портрет 11", tags: ["мода","портрети"], cover: false },
  { file: "gallery/editorial-12.jpg", album: "editorial", title: "Портрет 12", tags: ["мода","портрети"], cover: false },
  { file: "gallery/editorial-13.jpg", album: "editorial", title: "Портрет 13", tags: ["мода","портрети"], cover: false },
  { file: "gallery/editorial-15.jpg", album: "editorial", title: "Портрет 15", tags: ["мода","портрети"], cover: false },
  { file: "gallery/editorial-16.jpg", album: "editorial", title: "Портрет", tags: ["мода","портрети"], cover: true },
  { file: "gallery/editorial-17.jpg", album: "editorial", title: "Портрет 17", tags: ["мода","портрети"], cover: false },
  { file: "gallery/editorial-18.jpg", album: "editorial", title: "Портрет 18", tags: ["мода","портрети"], cover: false },
  { file: "gallery/editorial-20.jpg", album: "editorial", title: "Портрет 20", tags: ["мода","портрети"], cover: false },
  { file: "gallery/8.jpg", album: "produkti", title: "Рекламен кадър", tags: ["продукти"], cover: true },
  { file: "gallery/produkti-01.jpg", album: "produkti", title: "Продукт 1", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-02.jpg", album: "produkti", title: "Продукт 2", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-03.jpg", album: "produkti", title: "Продукт 3", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-05.jpg", album: "produkti", title: "Продукт 5", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-06.jpg", album: "produkti", title: "Продукт 6", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-07.jpg", album: "produkti", title: "Продукт 7", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-08.jpg", album: "produkti", title: "Продукт 8", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-10.jpg", album: "produkti", title: "Продукт 10", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-12.jpg", album: "produkti", title: "Продукт 12", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-13.jpg", album: "produkti", title: "Продукт 13", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-14.jpg", album: "produkti", title: "Продукт 14", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-15.jpg", album: "produkti", title: "Продукт 15", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-16.jpg", album: "produkti", title: "Продукт 16", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-17.jpg", album: "produkti", title: "Продукт 17", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-19.png", album: "produkti", title: "Продукт 19", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-20.jpg", album: "produkti", title: "Продукт 20", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-21.jpg", album: "produkti", title: "Продукт 21", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-22.jpg", album: "produkti", title: "Продукт 22", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-23.jpg", album: "produkti", title: "Продукт 23", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-24.jpg", album: "produkti", title: "Продукт 24", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-25.jpg", album: "produkti", title: "Продукт 25", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-26.jpg", album: "produkti", title: "Продукт 26", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-27.jpg", album: "produkti", title: "Продукт 27", tags: ["продукти"], cover: false },
  { file: "gallery/produkti-28.jpg", album: "produkti", title: "Продукт 28", tags: ["продукти"], cover: false },
  { file: "gallery/9.jpg", album: "katalog", title: "Каталог", tags: ["каталог"], cover: true },
  { file: "gallery/katalog-01.jpg", album: "katalog", title: "Каталог 1", tags: ["каталог"], cover: false },
  { file: "gallery/katalog-02.jpg", album: "katalog", title: "Каталог 2", tags: ["каталог"], cover: false },
  { file: "gallery/katalog-03.jpg", album: "katalog", title: "Каталог 3", tags: ["каталог"], cover: false },
  { file: "gallery/katalog-04.jpg", album: "katalog", title: "Каталог 4", tags: ["каталог"], cover: false },
  { file: "gallery/katalog-05.jpg", album: "katalog", title: "Каталог 5", tags: ["каталог"], cover: false },
  { file: "gallery/katalog-06.jpg", album: "katalog", title: "Каталог 6", tags: ["каталог"], cover: false },
  { file: "gallery/katalog-07.jpg", album: "katalog", title: "Каталог 7", tags: ["каталог"], cover: false },
  { file: "gallery/katalog-08.jpg", album: "katalog", title: "Каталог 8", tags: ["каталог"], cover: false },
  { file: "gallery/7.jpg", album: "konceptualna", title: "We rise to fall", tags: ["концептуална"], cover: true },
  { file: "gallery/konceptualna-01.jpg", album: "konceptualna", title: "Концептуална 1", tags: ["концептуална"], cover: false },
  { file: "gallery/konceptualna-02.jpg", album: "konceptualna", title: "Концептуална 2", tags: ["концептуална"], cover: false },
  { file: "gallery/konceptualna-03.jpg", album: "konceptualna", title: "Концептуална 3", tags: ["концептуална"], cover: false },
  { file: "gallery/konceptualna-04.jpg", album: "konceptualna", title: "Концептуална 4", tags: ["концептуална"], cover: false },
  { file: "gallery/konceptualna-05.jpg", album: "konceptualna", title: "Концептуална 5", tags: ["концептуална"], cover: false },
  { file: "gallery/konceptualna-06.jpg", album: "konceptualna", title: "Концептуална 6", tags: ["концептуална"], cover: false },
  { file: "gallery/konceptualna-07.jpg", album: "konceptualna", title: "Концептуална 7", tags: ["концептуална"], cover: false },
  { file: "gallery/konceptualna-08.jpg", album: "konceptualna", title: "Концептуална 8", tags: ["концептуална"], cover: false },
  { file: "gallery/konceptualna-09.jpg", album: "konceptualna", title: "Концептуална 9", tags: ["концептуална"], cover: false },
  { file: "gallery/konceptualna-10.jpg", album: "konceptualna", title: "Концептуална 10", tags: ["концептуална"], cover: false },
  { file: "gallery/konceptualna-11.jpg", album: "konceptualna", title: "Концептуална 11", tags: ["концептуална"], cover: false },
  { file: "gallery/konceptualna-12.jpg", album: "konceptualna", title: "Концептуална 12", tags: ["концептуална"], cover: false },
  { file: "gallery/konceptualna-13.jpg", album: "konceptualna", title: "Концептуална 13", tags: ["концептуална"], cover: false },
  { file: "gallery/konceptualna-14.jpg", album: "konceptualna", title: "Концептуална 14", tags: ["концептуална"], cover: false },
  { file: "gallery/konceptualna-15.jpg", album: "konceptualna", title: "Концептуална 15", tags: ["концептуална"], cover: false },
  { file: "gallery/konceptualna-16.jpg", album: "konceptualna", title: "Концептуална 16", tags: ["концептуална"], cover: false },
  { file: "gallery/konceptualna-17.jpg", album: "konceptualna", title: "Концептуална 17", tags: ["концептуална"], cover: false },
  { file: "gallery/konceptualna-19.jpg", album: "konceptualna", title: "Концептуална 19", tags: ["концептуална"], cover: false },
  { file: "gallery/konceptualna-20.jpg", album: "konceptualna", title: "Концептуална 20", tags: ["концептуална"], cover: false },
  { file: "gallery/421941886_7466156806738002_1655662125803631298_n.jpg", album: "portret", title: "Бизнес портрет", tags: ["портрет"], cover: true },
  { file: "gallery/portret-02.jpg", album: "portret", title: "Бизнес портрет 2", tags: ["портрет"], cover: false },
  { file: "gallery/portret-03.jpg", album: "portret", title: "Бизнес портрет 3", tags: ["портрет"], cover: false },
  { file: "gallery/portret-04.jpg", album: "portret", title: "Бизнес портрет 4", tags: ["портрет"], cover: false },
  { file: "gallery/portret-05.jpg", album: "portret", title: "Бизнес портрет 05", tags: ["портрет"], cover: false },
  { file: "gallery/portret-06.jpg", album: "portret", title: "Бизнес портрет 06", tags: ["портрет"], cover: false },
  { file: "gallery/portret-07.jpg", album: "portret", title: "Бизнес портрет 07", tags: ["портрет"], cover: false },
  { file: "gallery/svatbena-126.jpg", album: "svatbena", title: "Сватба", tags: ["сватбена"], cover: true },
  { file: "gallery/svatbena-127.jpg", album: "svatbena", title: "Сватба 127", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-128.jpg", album: "svatbena", title: "Сватба 128", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-129.jpg", album: "svatbena", title: "Сватба 129", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-130.jpg", album: "svatbena", title: "Сватба 130", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-131.jpg", album: "svatbena", title: "Сватба 131", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-49.jpg", album: "svatbena", title: "Сватба 49", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-50.jpg", album: "svatbena", title: "Сватба 50", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-51.jpg", album: "svatbena", title: "Сватба 51", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-52.jpg", album: "svatbena", title: "Сватба 52", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-53.jpg", album: "svatbena", title: "Сватба 53", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-54.jpg", album: "svatbena", title: "Сватба 54", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-55.jpg", album: "svatbena", title: "Сватба 55", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-56.jpg", album: "svatbena", title: "Сватба 56", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-132.jpg", album: "svatbena", title: "Сватба 132", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-133.jpg", album: "svatbena", title: "Сватба 133", tags: ["сватбена"], cover: false },
  { file: "gallery/4.jpg", album: "svatbena", title: "Сватба", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-01.jpg", album: "svatbena", title: "Сватба 1", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-03.jpg", album: "svatbena", title: "Сватба 3", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-05.jpg", album: "svatbena", title: "Сватба 5", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-06.jpg", album: "svatbena", title: "Сватба 6", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-07.jpg", album: "svatbena", title: "Сватба 7", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-09.jpg", album: "svatbena", title: "Сватба 9", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-10.jpg", album: "svatbena", title: "Сватба 10", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-11.jpg", album: "svatbena", title: "Сватба 11", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-13.jpg", album: "svatbena", title: "Сватба 13", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-15.jpg", album: "svatbena", title: "Сватба 15", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-16.jpg", album: "svatbena", title: "Сватба 16", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-18.jpg", album: "svatbena", title: "Сватба 18", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-19.jpg", album: "svatbena", title: "Сватба 19", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-20.jpg", album: "svatbena", title: "Сватба 20", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-21.jpg", album: "svatbena", title: "Сватба 21", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-22.jpg", album: "svatbena", title: "Сватба 22", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-23.jpg", album: "svatbena", title: "Сватба 23", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-24.jpg", album: "svatbena", title: "Сватба 24", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-25.jpg", album: "svatbena", title: "Сватба 25", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-26.jpg", album: "svatbena", title: "Сватба 26", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-27.jpg", album: "svatbena", title: "Сватба 27", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-28.jpg", album: "svatbena", title: "Сватба 28", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-29.jpg", album: "svatbena", title: "Сватба 29", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-30.jpg", album: "svatbena", title: "Сватба 30", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-57.jpg", album: "svatbena", title: "Сватба 57", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-58.jpg", album: "svatbena", title: "Сватба 58", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-59.jpg", album: "svatbena", title: "Сватба 59", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-60.jpg", album: "svatbena", title: "Сватба 60", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-61.jpg", album: "svatbena", title: "Сватба 61", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-62.jpg", album: "svatbena", title: "Сватба 62", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-63.jpg", album: "svatbena", title: "Сватба 63", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-64.jpg", album: "svatbena", title: "Сватба 64", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-65.jpg", album: "svatbena", title: "Сватба 65", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-66.jpg", album: "svatbena", title: "Сватба 66", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-67.jpg", album: "svatbena", title: "Сватба 67", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-68.jpg", album: "svatbena", title: "Сватба 68", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-69.jpg", album: "svatbena", title: "Сватба 69", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-70.jpg", album: "svatbena", title: "Сватба 70", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-71.jpg", album: "svatbena", title: "Сватба 71", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-72.jpg", album: "svatbena", title: "Сватба 72", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-73.jpg", album: "svatbena", title: "Сватба 73", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-74.jpg", album: "svatbena", title: "Сватба 74", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-75.jpg", album: "svatbena", title: "Сватба 75", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-76.jpg", album: "svatbena", title: "Сватба 76", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-77.jpg", album: "svatbena", title: "Сватба 77", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-78.jpg", album: "svatbena", title: "Сватба 78", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-79.jpg", album: "svatbena", title: "Сватба 79", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-80.jpg", album: "svatbena", title: "Сватба 80", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-81.jpg", album: "svatbena", title: "Сватба 81", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-82.jpg", album: "svatbena", title: "Сватба 82", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-83.jpg", album: "svatbena", title: "Сватба 83", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-84.jpg", album: "svatbena", title: "Сватба 84", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-85.jpg", album: "svatbena", title: "Сватба 85", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-86.jpg", album: "svatbena", title: "Сватба 86", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-87.jpg", album: "svatbena", title: "Сватба 87", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-88.jpg", album: "svatbena", title: "Сватба 88", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-89.jpg", album: "svatbena", title: "Сватба 89", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-90.jpg", album: "svatbena", title: "Сватба 90", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-91.jpg", album: "svatbena", title: "Сватба 91", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-92.jpg", album: "svatbena", title: "Сватба 92", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-93.jpg", album: "svatbena", title: "Сватба 93", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-94.jpg", album: "svatbena", title: "Сватба 94", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-95.jpg", album: "svatbena", title: "Сватба 95", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-96.jpg", album: "svatbena", title: "Сватба 96", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-97.jpg", album: "svatbena", title: "Сватба 97", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-98.jpg", album: "svatbena", title: "Сватба 98", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-99.jpg", album: "svatbena", title: "Сватба 99", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-100.jpg", album: "svatbena", title: "Сватба 100", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-102.jpg", album: "svatbena", title: "Сватба 102", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-104.jpg", album: "svatbena", title: "Сватба 104", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-105.jpg", album: "svatbena", title: "Сватба 105", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-106.jpg", album: "svatbena", title: "Сватба 106", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-107.jpg", album: "svatbena", title: "Сватба 107", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-108.jpg", album: "svatbena", title: "Сватба 108", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-109.jpg", album: "svatbena", title: "Сватба 109", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-110.jpg", album: "svatbena", title: "Сватба 110", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-111.jpg", album: "svatbena", title: "Сватба 111", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-112.jpg", album: "svatbena", title: "Сватба 112", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-114.jpg", album: "svatbena", title: "Сватба 114", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-116.jpg", album: "svatbena", title: "Сватба 116", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-117.jpg", album: "svatbena", title: "Сватба 117", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-118.jpg", album: "svatbena", title: "Сватба 118", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-119.jpg", album: "svatbena", title: "Сватба 119", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-120.jpg", album: "svatbena", title: "Сватба 120", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-121.jpg", album: "svatbena", title: "Сватба 121", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-122.jpg", album: "svatbena", title: "Сватба 122", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-123.jpg", album: "svatbena", title: "Сватба 123", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-124.jpg", album: "svatbena", title: "Сватба 124", tags: ["сватбена"], cover: false },
  { file: "gallery/svatbena-125.jpg", album: "svatbena", title: "Сватба 125", tags: ["сватбена"], cover: false },
  { file: "gallery/5.jpg", album: "balove", title: "Бал", tags: ["балове"], cover: true },
  { file: "gallery/balove-01.jpg", album: "balove", title: "Бал 1", tags: ["балове"], cover: false },
  { file: "gallery/balove-02.jpg", album: "balove", title: "Бал 2", tags: ["балове"], cover: false },
  { file: "gallery/balove-03.jpg", album: "balove", title: "Бал 3", tags: ["балове"], cover: false },
  { file: "gallery/balove-04.jpg", album: "balove", title: "Бал 4", tags: ["балове"], cover: false },
  { file: "gallery/balove-05.jpg", album: "balove", title: "Бал 5", tags: ["балове"], cover: false },
  { file: "gallery/balove-06.jpg", album: "balove", title: "Бал 6", tags: ["балове"], cover: false },
  { file: "gallery/balove-07.jpg", album: "balove", title: "Бал 7", tags: ["балове"], cover: false },
  { file: "gallery/balove-08.jpg", album: "balove", title: "Бал 8", tags: ["балове"], cover: false },
  { file: "gallery/balove-09.jpg", album: "balove", title: "Бал 9", tags: ["балове"], cover: false },
  { file: "gallery/balove-10.jpg", album: "balove", title: "Бал 10", tags: ["балове"], cover: false },
  { file: "gallery/balove-11.jpg", album: "balove", title: "Бал 11", tags: ["балове"], cover: false },
  { file: "gallery/balove-12.jpg", album: "balove", title: "Бал 12", tags: ["балове"], cover: false },
  { file: "gallery/balove-13.jpg", album: "balove", title: "Бал 13", tags: ["балове"], cover: false },
  { file: "gallery/balove-15.jpg", album: "balove", title: "Бал 15", tags: ["балове"], cover: false },
  { file: "gallery/balove-16.jpg", album: "balove", title: "Бал 16", tags: ["балове"], cover: false },
  { file: "gallery/balove-17.jpg", album: "balove", title: "Бал 17", tags: ["балове"], cover: false },
  { file: "gallery/balove-18.jpg", album: "balove", title: "Бал 18", tags: ["балове"], cover: false },
  { file: "gallery/balove-19.jpg", album: "balove", title: "Бал 19", tags: ["балове"], cover: false },
  { file: "gallery/balove-20.jpg", album: "balove", title: "Бал 20", tags: ["балове"], cover: false },
  { file: "gallery/balove-21.jpg", album: "balove", title: "Бал 21", tags: ["балове"], cover: false },
  { file: "gallery/balove-22.jpg", album: "balove", title: "Бал 22", tags: ["балове"], cover: false },
  { file: "gallery/balove-23.jpg", album: "balove", title: "Бал 23", tags: ["балове"], cover: false },
  { file: "gallery/balove-24.jpg", album: "balove", title: "Бал 24", tags: ["балове"], cover: false },
  { file: "gallery/6.jpg", album: "krustene", title: "Кръщене", tags: ["кръщене"], cover: true },
  { file: "gallery/krustene-01.jpg", album: "krustene", title: "Кръщене 1", tags: ["кръщене"], cover: false },
  { file: "gallery/krustene-02.jpg", album: "krustene", title: "Кръщене 2", tags: ["кръщене"], cover: false },
  { file: "gallery/krustene-03.jpg", album: "krustene", title: "Кръщене 3", tags: ["кръщене"], cover: false },
  { file: "gallery/krustene-04.jpg", album: "krustene", title: "Кръщене 4", tags: ["кръщене"], cover: false },
  { file: "gallery/krustene-05.jpg", album: "krustene", title: "Кръщене 5", tags: ["кръщене"], cover: false },
  { file: "gallery/krustene-06.jpg", album: "krustene", title: "Кръщене 6", tags: ["кръщене"], cover: false },
  { file: "gallery/krustene-07.jpg", album: "krustene", title: "Кръщене 7", tags: ["кръщене"], cover: false },
  { file: "gallery/krustene-08.jpg", album: "krustene", title: "Кръщене 8", tags: ["кръщене"], cover: false },
  { file: "gallery/krustene-09.jpg", album: "krustene", title: "Кръщене 9", tags: ["кръщене"], cover: false },
  { file: "gallery/krustene-10.jpg", album: "krustene", title: "Кръщене 10", tags: ["кръщене"], cover: false },
  { file: "gallery/krustene-11.jpg", album: "krustene", title: "Кръщене 11", tags: ["кръщене"], cover: false },
  { file: "gallery/krustene-12.jpg", album: "krustene", title: "Кръщене 12", tags: ["кръщене"], cover: false },
  { file: "gallery/krustene-13.jpg", album: "krustene", title: "Кръщене 13", tags: ["кръщене"], cover: false },
  { file: "gallery/krustene-14.jpg", album: "krustene", title: "Кръщене 14", tags: ["кръщене"], cover: false },
  { file: "gallery/krustene-15.jpg", album: "krustene", title: "Кръщене 15", tags: ["кръщене"], cover: false },
  { file: "gallery/krustene-16.jpg", album: "krustene", title: "Кръщене 16", tags: ["кръщене"], cover: false },
  { file: "gallery/krustene-17.jpg", album: "krustene", title: "Кръщене 17", tags: ["кръщене"], cover: false }
];
